// ============================================================
// DESIGN TOKENS - visual layer only.
// Generated by: tools/run-onepage.mjs (generateDesignTs)
// ============================================================

export type HeroWeight = "light" | "regular" | "bold";
export type HeroAccent = "underline" | "color" | "none";
export type AccentIntensity = "full" | "subtle";
export type BackgroundVariant =
  | "dot-grid"
  | "dot-grid-light"
  | "line-grid"
  | "line-grid-light"
  | "particles"
  | "particles-light"
  | "soft-orbs"
  | "minimal-flat";

export interface ColorsConfig {
  source: string;
  sourceNote: string;
  usageNotes: string[];
  primary: string;
  primaryHover: string;
  primarySoft: string;
  primaryForeground: string;
  primaryHex: string;
  secondary: string;
  secondarySoft: string;
}

export interface VisualTreatment {
  heroWeight: HeroWeight;
  heroAccent: HeroAccent;
  accentIntensity: AccentIntensity;
}

export interface BackgroundConfig {
  variant: BackgroundVariant;
}

export type CtaStyle = "default";

export interface CtaDesignConfig {
  style: CtaStyle;
}

export interface DesignConfig {
  colors: ColorsConfig;
  visualTreatment: VisualTreatment;
  background: BackgroundConfig;
  cta: CtaDesignConfig;
}

const design: DesignConfig = {
  "colors": {
    "source": "design_pack",
    "sourceNote": "Palette defined in output/design-pack.json",
    "usageNotes": [],
    "primary": "199 100% 42%",
    "primaryHover": "210 100% 28%",
    "primarySoft": "199 60% 93%",
    "primaryForeground": "0 0% 100%",
    "primaryHex": "#0092d6",
    "secondary": "",
    "secondarySoft": "199 60% 93%"
  },
  "visualTreatment": {
    "heroWeight": "bold",
    "heroAccent": "color",
    "accentIntensity": "full"
  },
  "background": {
    "variant": "minimal-flat"
  },
  "cta": {
    "style": "default"
  }
};

export default design;
